---
- name: manage libvirt guests 
  user: ansible 
  hosts: baremetal
  vars:
      project_name: web
      number_of_hosts: 3
      os_type: rhel
  
  tasks:
    - name: stop all project VMs - {{ os_type }}-{{ project_name }}{{ item }}
      virt:
          name: "{{ os_type }}-{{ project_name }}{{ item }}"
          state: destroyed
      with_sequence: count={{ number_of_hosts }}

    - name: drop VM {{ project_name }} VM config with disks
      command: "virsh undefine {{ os_type }}-{{ project_name }}{{ item }} --remove-all-storage"
      with_sequence: count={{ number_of_hosts }}
    
