---
- name: Setup Zabbix client
  user: ansible 
  hosts: rhel_vms

  tasks:
    - name: Install Zabbix agent
      yum: 
        name: zabbix30-agent
        state: latest 

#     - name: Install Zabbix API
#       yum: 
#         name: python-pyzabbix
#         state: latest 

    - name: make sure zabbix client service is enabled
      systemd:
        name: zabbix-agent
        enabled: yes

    - name: Create a new host or update an existing host's info
      local_action:
        module: zabbix_host
        server_url: http://zabbix/zabbix
        login_user: Admin
        login_password: zabbix
        host_name: "{{ inventory_hostname }}"
        visible_name: "{{ inventory_hostname }}"
        description: This is the {{ inventory_hostname }} description
        inventory_mode: manual
        host_groups:
          - RHEL Servers
        link_templates:
          - Template App HTTP Service
          - Template App SSH Service
          - Template Module ICMP Ping
          - Template OS Linux
        status: enabled
        state: absent
        interfaces: 
          - type: agent
            main: 1
            dns: "{{ inventory_hostname }}"
            ip: "{{ ansible_eth0.ipv4.address }}"

    - name: make sure zabbix client is running
      systemd:
        name: zabbix-agent
        state: started

