---
- name: manage libvirt guests 
  user: ansible 
  hosts: baremetal
  vars:
      host_name: web
      number_of_hosts: 2
  
  tasks:
    - name: stop all project VMs - {{ host_name }}{{ item }}
      virt:
          name: "{{ host_name }}{{ item }}"
          state: destroyed
      with_sequence: count={{ number_of_hosts }}

    - name: drop VM {{ host_name }} VM config with disks
      command: "virsh undefine {{ host_name }}{{ item }} --remove-all-storage"
      with_sequence: count={{ number_of_hosts }}
    
