---
- name: manage libvirt guests 
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: web
      number_of_hosts: 3

  tasks:
# not going to do xml_lookup just for a template, thank you. 
# going with 'command" module and virt-clone
    - name: create VM {{ project_name }} {{ item }} by cloning image
      command: "virt-clone --original=rhel7base-clone --name={{ project_name }}{{ item }} --auto-clone"
      with_sequence: count={{ number_of_hosts }}

    - name: sysprep VM {{ project_name }}{{ item }}
      command: "virt-sysprep -d {{ project_name }}{{ item }} --hostname {{ project_name }}{{ item }} --operations defaults,-ssh-userdir" 
      with_sequence: count={{ number_of_hosts }}
    
- name: start new guests 
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: web
      number_of_hosts: 3

  tasks:
    - name: start VM "{{ project_name }}{{ item }}"
      virt:
          name: "{{ project_name }}{{ item }}"
          state: running
      with_sequence: count={{ number_of_hosts }}

    - name: allow DHCP/DNS to register
      pause:
        minutes: 1
