---
- name: manage libvirt guests 
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: C
  
  tasks:
    - name: stop all project VMs - Project{{ project_name }}1
      virt:
          name: Project{{ project_name }}1
          state: destroyed

    - name: stop all project VMs - Project{{ project_name }}2
      virt:
          name: Project{{ project_name }}2
          state: destroyed

    - name: stop all project VMs - Project{{ project_name }}3
      virt:
          name: Project{{ project_name }}3
          state: destroyed

- name: remove disks of VMs
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: C
  
  tasks:
    - name: drop Project{{ project_name }}1 VM config
      command: "virsh undefine Project{{ project_name }}1 --remove-all-storage"
    - name: drop project {{ project_name }} VM 2 config
      command: "virsh undefine Project{{ project_name }}2 --remove-all-storage"
    - name: drop project {{ project_name }} VM 3 config
      command: "virsh undefine Project{{ project_name }}3 --remove-all-storage"
    
