---
- name: manage libvirt guests 
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: web
      number_of_hosts: 3
  
  tasks:
    - name: stop all project VMs - {{ project_name }}{{ item }}
      virt:
          name: "{{ project_name }}{{ item }}"
          state: destroyed
      with_sequence: count={{ number_of_hosts }}


- name: remove disks of VMs
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: web
      number_of_hosts: 3
  
  tasks:
    - name: drop VM {{ project_name }}{{ item }} VM config
      command: "virsh undefine {{ project_name }}{{ item }} --remove-all-storage"
      with_sequence: count={{ number_of_hosts }}
    
