---
- name: manage libvirt guests 
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: D
  
  tasks:
    - name: stop all project VMs - {{ project_name }}win1
      virt:
          name: "{{ project_name }}win1"
          state: destroyed

- name: remove disks of VMs
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: D
  
  tasks:
    - name: drop {{ project_name }}win1 VM config
      command: "virsh undefine {{ project_name }}win1 --remove-all-storage"
    
