---
- name: manage libvirt guests 
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: D

  tasks:
# not going to do xml_lookup just for a template, thank you. 
# going with 'command" module and virt-clone
    - name: create VM {{ project_name }}win1 by cloning image
      command: "virt-clone --original=win-image --name={{ project_name }}win1 --auto-clone"

- name: start new VM
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: D

  tasks:
    - name: start VM {{ project_name }}win1
      virt:
          name: "{{ project_name }}win1"
          state: running
    
    - name: allow DHCP/DNS to register
      pause:
        minutes: 1
