---
- name: manage libvirt guests 
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: web
      number_of_hosts: 1
      os_type: win


  tasks:
# not going to do xml_lookup just for a template, thank you. 
# going with 'command" module and virt-clone
    - name: create VM {{ project_name }}-{{os_type}} by cloning image
      command: "virt-clone --original=win-image --name={{ project_name }}-{{ os_type }}{{ item }} --auto-clone"
      with_sequence: count={{ number_of_hosts }}

- name: start new VM
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: web
      number_of_hosts: 1

  tasks:
    - name: start VM {{ project_name }}-{{ os_type }}
      virt:
          name: "{{ project_name }}-{{ os_type }}{{ item }}"
          state: running
      with_sequence: count={{ number_of_hosts }}
    
    - name: allow DHCP/DNS to register
      pause:
        minutes: 1
