---
- name: manage libvirt guests 
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: web
      number_of_hosts: 1
      os_type: win


  tasks:
# not going to do xml_lookup just for a template, thank you. 
# going with 'command" module and virt-clone
    - name: create VM {{ os_type }}-{{ project_name }} items by cloning image
      command: "virt-clone --original=win-image --name={{ os_type }}-{{ project_name }}{{ item }} --auto-clone"
      with_sequence: count={{ number_of_hosts }}

- name: start new VM
  user: ansible 
  hosts: barelaptop
  vars:
      project_name: web
      number_of_hosts: 1
      os_type: win

  tasks:
    - name: start VM {{ os_type }}-{{ project_name }} items
      virt:
          name: "{{ os_type }}-{{ project_name }}{{ item }}"
          state: running
      with_sequence: count={{ number_of_hosts }}
    
    - name: allow DHCP/DNS to register
      pause:
        minutes: 1
