---
- name: set local hostname 
  hosts: win_vms

  tasks:
    - name: Change the hostname to new_hostname
      win_hostname:
        name: "{{ inventory_hostname }}"
      register: res

    - name: reboot to get new hostname take effect
      win_reboot: 
#      when: res.reboot_required
