---
- name: Ping
  hosts: win_vms
  vars:
    ansible_user: Administrator
    ansible_password: TotalSecret!
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: basic

  tasks:
    - name: pingpong
      win_ping:
